# Generated by Django 4.2 on 2023-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('apartment', models.CharField(max_length=50)),
                ('account', models.IntegerField(max_length=50)),
                ('password', models.IntegerField(max_length=50)),
            ],
        ),
    ]
