# Generated by Django 4.2 on 2023-04-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users_leader_alter_users_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='workAccount',
            field=models.IntegerField(null=True),
        ),
    ]
