# Generated by Django 4.2 on 2023-04-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='weekNumber',
            field=models.IntegerField(null=True),
        ),
    ]
