# Generated by Django 4.2 on 2023-05-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_users_submittimt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='submitTimt',
            new_name='submitTime',
        ),
    ]
