# Generated by Django 4.2 on 2023-05-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_users_submittime_memory_submittime'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='numbering',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
