# Generated by Django 4.2 on 2023-05-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_project_leadername'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='leaderId',
            field=models.IntegerField(null=True),
        ),
    ]
