# Generated by Django 4.2 on 2023-05-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_memory_leaderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='saveTime',
            field=models.DateField(null=True),
        ),
    ]
